name = "smallseyss"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."

[site]
bucket = "./dist"
include = ["**/*"]
exclude = ["node_modules/*"]

[build.upload]
format = "service-worker" 